### ISSUE TITLE
Sir, what is the meaning of FirstEndWifiWormTunnel

### ISSUE THREAD

**Issue by SimonHu-HN** [cjamadagni/Wormhole-Attack-in-NS3#9]
Sir, could you tell me what the specific meaning of the following four variables is?

FirstEndWifiWormTunnel
SecondEndWifiWormTunnel
FirstEndOfWormTunnel
SecondEndOfWormTunnel

Thanks in advance

**Comment by anjuman77** [comment]
Sir
I installed ns-3.24 to run your code as you mentioned in your blog, but aodv-rtable.h file not found. Where to put the 4 files you provided in ns3? How to get the header file?
